### ISSUE TITLE
Can no longer deny authorization requests with 2.2.1

### ISSUE THREAD

**Issue by nvoigt** [LaunchKey/launchkey-android-whitelabel-sdk#12]
The X in the top left corner no longer appears when an authorization request pops up giving the user no way to deny a request. Did the method or flow for authorization denial change in this version?

**Comment by arjleon** [comment]
Starting 2.2.1, the embedded Toolbar view is set to hidden by default. This was made based on previous feedback since it led to double toolbars if the hosting Activity had one already (which is a really common pattern when embedding Fragments). 

You can easily turn the toolbar back to visible via `.setToolbarVisible(true)`. You can refer to the last bit of this [section](https://docs.launchkey.com/developer/white-label/integrate-white-label-sdk-android-v2.html#interacting-with-an-auth-request).

**Comment by nvoigt** [comment]
I'm still confused. If the toolbar is disabled by default what is the preferred method for the user to deny a request? Is there another method call to do it manually? That seems like a core feature of the authorization screen and doesn't make a lot of sense to disable or enable on the authorization fragment.

**Comment by arjleon** [comment]
Well the `AuthRequestFragment` has a `deny()` method so it can be called if custom UI is provided. If you want to the Toolbar to be shown, then calling `.setToolbarVisible(true)` on the fragment should do the job. 

To avoid confusion in the future we might have a minor release showing the Toolbar with the deny option shown by default once again.

Let me know if you need more help.

[Docs on `AuthRequestFragment`](https://docs.launchkey.com/developer/white-label/integrate-white-label-sdk-android-v2.html#interacting-with-an-auth-request)

**Comment by arjleon** [comment]
Closing issue. By calling the methods mentioned above, the Toolbar can be made visible. There's also reference to the web docs on `AuthRequestFragment`.
